apiVersion: v1
kind: Service
metadata:
  name: restaurant-api-nodeport
  namespace: forge-restaurant
  labels:
    app: restaurant-api
    project: signalforge
spec:
  type: NodePort
  selector:
    app: restaurant-api
  ports:
  - name: http
    port: 80
    targetPort: http
    nodePort: 30080
