apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: forge-observability
  labels:
    app: prometheus
    project: signalforge
spec:
  type: ClusterIP
  selector:
    app: prometheus
  ports:
  - name: web
    port: 9090
    targetPort: web

