apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: forge-observability
  labels:
    app: prometheus
    project: signalforge
data:
  prometheus.yml: |
    global:
      scrape_interval: 30s
      scrape_timeout: 10s
      evaluation_interval: 30s

    scrape_configs:
    - job_name: restaurant-api
      metrics_path: /metrics
      kubernetes_sd_configs:
      - role: pod
        namespaces:
          names:
          - forge-restaurant
      relabel_configs:
      - action: keep
        source_labels:
        - __meta_kubernetes_pod_label_app
        regex: restaurant-api
      - action: keep
        source_labels:
        - __meta_kubernetes_pod_container_name
        regex: restaurant-api
      - action: keep
        source_labels:
        - __meta_kubernetes_pod_container_port_name
        regex: http
      - action: replace
        source_labels:
        - __meta_kubernetes_namespace
        target_label: namespace
      - action: replace
        source_labels:
        - __meta_kubernetes_pod_name
        target_label: pod
      - action: replace
        source_labels:
        - __meta_kubernetes_pod_node_name
        target_label: node
      - action: replace
        source_labels:
        - __meta_kubernetes_pod_phase
        target_label: pod_phase
      - action: replace
        source_labels:
        - __meta_kubernetes_pod_ready
        target_label: pod_ready
