version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "America/New_York"
    open-pull-requests-limit: 5
    groups:
      workflow-actions:
        patterns:
          - "*"

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "America/New_York"
    open-pull-requests-limit: 5
    groups:
      forgeops-build-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "pip"
    directory: "/apps/restaurant-api"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "America/New_York"
    open-pull-requests-limit: 5
    groups:
      restaurant-api-python:
        patterns:
          - "*"

  - package-ecosystem: "npm"
    directory: "/apps/forge-yaml-workbench"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "America/New_York"
    open-pull-requests-limit: 5
    groups:
      workbench-node:
        patterns:
          - "*"

  - package-ecosystem: "docker"
    directory: "/apps/restaurant-api"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "America/New_York"
    open-pull-requests-limit: 5
    groups:
      restaurant-api-base-images:
        patterns:
          - "*"

  - package-ecosystem: "docker"
    directory: "/apps/forge-yaml-workbench"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "America/New_York"
    open-pull-requests-limit: 5
    groups:
      workbench-base-images:
        patterns:
          - "*"
