apiVersion: 1
datasources:
- name: SignalForge Loki
  uid: signalforge-loki
  type: loki
  access: proxy
  url: http://loki.forge-observability.svc.cluster.local:3100
  isDefault: false
  editable: false
