apiVersion: 1
datasources:
- name: SignalForge Prometheus
  uid: signalforge-prometheus
  type: prometheus
  access: proxy
  url: http://prometheus.forge-observability.svc.cluster.local:9090
  isDefault: true
  editable: false
  jsonData:
    timeInterval: 30s
    httpMethod: POST
