apiVersion: v1
kind: Service
metadata:
  name: service-pulse-board
  namespace: forge-pulse
  labels:
    app: service-pulse-board
    project: signalforge
    app.kubernetes.io/name: service-pulse-board
    app.kubernetes.io/part-of: signalforge
spec:
  type: ClusterIP
  selector:
    app: service-pulse-board
  ports:
  - name: http
    port: 8080
    targetPort: http
    protocol: TCP
