apiVersion: v1
kind: PersistentVolume
metadata:
  name: loki-local-nvme
  labels:
    app: loki
    project: signalforge
spec:
  capacity:
    storage: 8Gi
  volumeMode: Filesystem
  accessModes: [ReadWriteOnce]
  persistentVolumeReclaimPolicy: Retain
  storageClassName: signalforge-local-nvme
  claimRef:
    namespace: forge-observability
    name: loki-data
  local:
    path: /mnt/signalforge-loki/data
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values: [forge-head]
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: loki-data
  namespace: forge-observability
  labels:
    app: loki
    project: signalforge
spec:
  accessModes: [ReadWriteOnce]
  volumeMode: Filesystem
  storageClassName: signalforge-local-nvme
  volumeName: loki-local-nvme
  resources:
    requests:
      storage: 8Gi
