apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana-local-nvme
  labels:
    app: grafana
    project: signalforge
spec:
  capacity:
    storage: 3Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: signalforge-local-nvme
  claimRef:
    namespace: forge-observability
    name: grafana-data
  local:
    path: /mnt/signalforge-grafana/data
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - forge-head
