export const SAMPLE_YAML = [
  "apiVersion: apps/v1",
  "kind: Deployment",
  "metadata:",
  "  name: restaurant-api",
  "  namespace: forge-restaurant",
  "  labels:",
  "    app: restaurant-api",
  "spec:",
  "  replicas: 3",
  "  selector:",
  "    matchLabels:",
  "      app: restaurant-api",
  "  template:",
  "    metadata:",
  "      labels:",
  "        app: restaurant-api",
  "    spec:",
  "      automountServiceAccountToken: false",
  "      containers:",
  "        - name: restaurant-api",
  "          image: wmstipes/signalforge-restaurant-api:0.7.0",
  "          ports:",
  "            - name: http",
  "              containerPort: 8000",
  "          readinessProbe:",
  "            httpGet:",
  "              path: /ready",
  "              port: http",
  "          livenessProbe:",
  "            httpGet:",
  "              path: /health",
  "              port: http",
  "          resources:",
  "            requests:",
  "              cpu: 100m",
  "              memory: 128Mi",
  "            limits:",
  "              cpu: 500m",
  "              memory: 512Mi",
  "---",
  "apiVersion: v1",
  "kind: Service",
  "metadata:",
  "  name: restaurant-api",
  "  namespace: forge-restaurant",
  "spec:",
  "  type: ClusterIP",
  "  selector:",
  "    app: restaurant-api",
  "  ports:",
  "    - name: http",
  "      port: 80",
  "      targetPort: http",
  ""
].join("\n");
