apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: forgeops-console-auth
  namespace: forge-console
spec:
  basicAuth:
    secret: forgeops-console-auth
    realm: ForgeOps Console
    removeHeader: true
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: forgeops-console
  namespace: forge-console
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: forge-console-forgeops-console-auth@kubernetescrd
spec:
  ingressClassName: traefik
  rules:
    - host: forgeops.forge.home.arpa
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: forgeops-console
                port:
                  number: 9090
