apiVersion: v1
kind: Service
metadata:
  name: forge-yaml-workbench
  namespace: forge-tools
  labels:
    app: forge-yaml-workbench
    project: signalforge
    app.kubernetes.io/name: forge-yaml-workbench
    app.kubernetes.io/part-of: signalforge
spec:
  type: NodePort
  selector:
    app: forge-yaml-workbench
  ports:
  - name: http
    port: 80
    targetPort: http
    nodePort: 30081
    protocol: TCP
